"use client";

import { FileText, Download, Calendar, BarChart3 } from 'lucide-react';

interface SampleReport {
    id: string;
    name: string;
    documentName: string;
    date: string;
    score: number;
    frameworks: string[];
    pdfPath: string;
}

const sampleReports: SampleReport[] = [
    {
        id: '1',
        name: 'LFR DPIA Compliance Report',
        documentName: 'lfr-dpia.pdf',
        date: '2025-12-11',
        score: 60,
        frameworks: ['UK ICO', 'UK DPA/GDPR', 'EU AI Act', 'ISO 42001'],
        pdfPath: '/samples/lfr-dpia_compliance_report.pdf',
    },
];

function getScoreColor(score: number): string {
    if (score >= 70) return 'text-green-600';
    if (score >= 50) return 'text-yellow-600';
    return 'text-red-600';
}

function getScoreBg(score: number): string {
    if (score >= 70) return 'bg-green-100';
    if (score >= 50) return 'bg-yellow-100';
    return 'bg-red-100';
}

export function SampleReports() {
    if (sampleReports.length === 0) return null;

    return (
        <div className="bg-white rounded-lg border border-gray-200 p-6 mb-6">
            <div className="flex items-center gap-2 mb-4">
                <FileText className="w-5 h-5 text-blue-600" />
                <h3 className="text-lg font-semibold text-gray-900">Sample Reports</h3>
                <span className="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded-full">
                    Portfolio Examples
                </span>
            </div>

            <p className="text-sm text-gray-600 mb-4">
                Example compliance reports generated by this tool. Download to see the detailed analysis output.
            </p>

            <div className="space-y-3">
                {sampleReports.map((report) => (
                    <div
                        key={report.id}
                        className="flex items-center justify-between p-4 bg-gray-50 rounded-lg border border-gray-100 hover:border-blue-200 transition-colors"
                    >
                        <div className="flex items-center gap-4">
                            <div className={`p-2 rounded-lg ${getScoreBg(report.score)}`}>
                                <BarChart3 className={`w-5 h-5 ${getScoreColor(report.score)}`} />
                            </div>
                            <div>
                                <h4 className="font-medium text-gray-900">{report.name}</h4>
                                <div className="flex items-center gap-3 text-xs text-gray-500 mt-1">
                                    <span className="flex items-center gap-1">
                                        <Calendar className="w-3 h-3" />
                                        {new Date(report.date).toLocaleDateString('en-GB', {
                                            day: 'numeric',
                                            month: 'short',
                                            year: 'numeric',
                                        })}
                                    </span>
                                    <span>•</span>
                                    <span>{report.frameworks.length} frameworks</span>
                                </div>
                            </div>
                        </div>

                        <div className="flex items-center gap-4">
                            <div className={`text-lg font-bold ${getScoreColor(report.score)}`}>
                                {report.score}%
                            </div>
                            <a
                                href={report.pdfPath}
                                download
                                className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors"
                            >
                                <Download className="w-4 h-4" />
                                Download
                            </a>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
